version: "3.7"
services:
  be:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./be
      dockerfile: Dockerfile
    environment:
        POSTGRES_DB: db
    container_name: be-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./be:/var/www
    depends_on:
      - db
    networks:
      - todonetwork
  
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    depends_on:
      - db
      - be
    ports: 
      - "3000:3000"
    networks:
      - todonetwork


  nginx:
    image: nginx:alpine
    container_name: be-nginx
    ports:
      - "8000:80"
    volumes:
      - ./be:/var/www
      - ./be/nginx/todo.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
    networks:
      - todonetwork

  db:
    image: postgres
    container_name: be-pgsql
    volumes:
        - db_data:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=rushdb
        - POSTGRES_USER=mahdi
        - POSTGRES_PASSWORD=0000  
    ports:
        - "5432:5432"
    networks:
      - todonetwork
volumes:
    db_data:

networks:
  todonetwork:
    driver: bridge

   
 